from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.maximize_window()
driver.get("https://wisdomofreddit.com/")
enter_val=input("Enter the values")
time.sleep(2)
enter_text=driver.find_element_by_xpath("//input[@name='query']").send_keys(enter_val)
time.sleep(3)
serch=driver.find_element_by_xpath("//button[text()='Find me some tangents!']").click()
time.sleep(3)
url1=input("Enter the url")
time.sleep(3)
driver.get(url1)
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
why_w=driver.find_element_by_xpath("//a[text()='Why']").click()
time.sleep(3)
this_art=driver.find_element_by_xpath("//a[text()='this article']").click()
time.sleep(5)
driver.back()
time.sleep(2)
uses_w=driver.find_element_by_xpath("//a[text()='Uses']").click()
time.sleep(2)
uses_1=driver.find_element_by_xpath('//a[@href="/search?query=%22lived+in+moscow%22"]').click()
time.sleep(3)
driver.back()
protips_w=driver.find_element_by_xpath("//a[text()='Pro tips']").click()
time.sleep(2)
eg_w=driver.find_element_by_xpath("//a[text()='Examples']").click()
time.sleep(2)
blog_w=driver.find_element_by_xpath("//a[text()='Blog']").click()
time.sleep(2)
about_w=driver.find_element_by_xpath("//a[text()='About']").click()
time.sleep(2)
logo_1=driver.find_element_by_xpath("//img[@src='/static/img/wor_logo.png']").click()
time.sleep(3)

driver.close()
